apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: demowebapp
          image: registry.gitlab.com/unicorn/unicornapp:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: mysql-prod
            - name: MYSQK_USER
              valueFrom:
                secretKeyRef:
                  name: datasource-credentials
                  key: dbuser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource-credentials
                  key: dbpassword